"""Object storage port — abstracts local FS, S3, Supabase Storage, R2, MinIO, etc."""
from typing import Protocol, runtime_checkable


@runtime_checkable
class ObjectStore(Protocol):
    def upload(self, key: str, content: bytes, content_type: str) -> None: ...
    def download(self, key: str) -> bytes: ...
    def signed_url(self, key: str, ttl_seconds: int = 3600) -> str: ...
    def delete(self, key: str) -> None: ...
    def health_check(self) -> tuple[bool, str]: ...
